# Generated by Django 2.2 on 2020-11-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=50, verbose_name='网站名称')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='网站描述')),
                ('link', models.URLField(help_text='请填写http或https开头的完整形式地址', verbose_name='友链地址')),
                ('logo', models.URLField(blank=True, help_text='请填写http或https开头的完整形式地址', verbose_name='网站LOGO')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否首页展示')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
                'ordering': ['create_date'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('text', models.TextField(default='暂无公告', verbose_name='公告')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否开启标志')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
            },
        ),
        migrations.CreateModel(
            name='Rotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('number', models.IntegerField(help_text='图片不要多于5张', verbose_name='播放顺序编号')),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='标题')),
                ('img_link', models.ImageField(blank=True, default='upimage/default1.png', null=True, upload_to='rotation_img/%Y/%m', verbose_name='图片地址')),
                ('url', models.CharField(default='#', max_length=200, verbose_name='跳转链接')),
            ],
            options={
                'verbose_name': '图片轮播',
                'verbose_name_plural': '图片轮播',
                'ordering': ['number', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '博客内容', 'verbose_name_plural': '博客内容'},
        ),
        migrations.AlterField(
            model_name='article',
            name='img_link',
            field=models.ImageField(blank=True, default='upimage/default1.png', null=True, upload_to='article_img/%Y/%m', verbose_name='图片地址'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(default='作者懒的写摘要', verbose_name='文章摘要'),
        ),
    ]
