# Generated by Django 2.2 on 2020-11-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20201110_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigcategory',
            name='is_show',
            field=models.BooleanField(default=False, verbose_name='是否有二级标签'),
        ),
    ]
