# Generated by Django 2.2 on 2020-11-11 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20201111_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['create_date'], 'verbose_name': '博客内容', 'verbose_name_plural': '博客内容'},
        ),
        migrations.AddField(
            model_name='article',
            name='creat_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='实体生成日期'),
        ),
        migrations.AddField(
            model_name='bigcategory',
            name='creat_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='实体生成日期'),
        ),
        migrations.AddField(
            model_name='category',
            name='creat_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='实体生成日期'),
        ),
        migrations.AddField(
            model_name='friendlink',
            name='creat_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='实体生成日期'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='creat_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='实体生成日期'),
        ),
        migrations.AddField(
            model_name='notice',
            name='creat_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='实体生成日期'),
        ),
        migrations.AddField(
            model_name='rotation',
            name='creat_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='实体生成日期'),
        ),
        migrations.AddField(
            model_name='tag',
            name='creat_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='实体生成日期'),
        ),
    ]
