# Generated by Django 2.2 on 2020-11-11 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20201111_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-create_date'], 'verbose_name': '博客内容', 'verbose_name_plural': '博客内容'},
        ),
    ]
