# Generated by Django 2.2 on 2020-11-11 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20201111_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='bigcategory',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='friendlink',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='keyword',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='rotation',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='creat_time',
            new_name='create_time',
        ),
    ]
