# Generated by Django 2.2 on 2020-11-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20201112_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotation',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='播放顺序编号'),
        ),
    ]
