# Generated by Django 2.2 on 2020-11-22 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20201122_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bigcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='articles.BigCategory', verbose_name='文章大分类'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='articles.Category', verbose_name='文章二级分类'),
        ),
    ]
