# Generated by Django 2.2 on 2020-12-01 16:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_auto_20201125_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateField(default=datetime.datetime.now, verbose_name='实体生成日期')),
                ('nickname', models.CharField(max_length=20, verbose_name='昵称')),
                ('email', models.CharField(max_length=30, verbose_name='邮箱')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('belong', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.Article', verbose_name='所属文章')),
            ],
            options={
                'verbose_name': '评论内容',
                'verbose_name_plural': '评论内容',
            },
        ),
    ]
