# Generated by Django 2.2 on 2020-12-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_commentuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentuser',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='邮箱'),
        ),
    ]
