# Generated by Django 2.2 on 2020-12-09 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_auto_20201201_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateField(default=datetime.datetime.now, verbose_name='实体生成日期')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('body', models.TextField(verbose_name='文章内容')),
                ('summary', models.TextField(default='作者懒的写摘要', verbose_name='文章摘要')),
                ('img_link', models.ImageField(blank=True, default='upimage/default1.png', null=True, upload_to='article_img/%Y/%m', verbose_name='图片地址')),
                ('slug', models.SlugField(help_text='请务必填写', null=True, unique=True)),
            ],
            options={
                'verbose_name': '每日必读',
                'verbose_name_plural': '每日必读',
            },
        ),
    ]
