# Generated by Django 2.2 on 2020-12-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_daily_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_article',
            name='img_link',
            field=models.ImageField(blank=True, default='upimage/default1.png', null=True, upload_to='daily_article_img/%Y/%m', verbose_name='图片地址'),
        ),
    ]
